Changing Planning Pipeline Reference
PilzDE/pilz_templates pull request #15
Opened 2020-02-19 12:37 UTC by ct2034

to match https://github.com/ros-planning/moveit/pull/1893

2020-02-19 12:49 UTC, ct2034 commented
TODO: Add info to changelog after https://github.com/PilzDE/pilz_application_templates/pull/13

2021-07-12 10:07 UTC, rfeistenauer commented on prbt_default_application/CHANGELOG.rst
> +* compatible with pilz_robots version melodic 0.5.22 and noetic-0.6.0
```suggestion
* compatible with pilz_robots version melodic-0.5.22 and noetic-0.6.0
```

2021-07-12 16:17 UTC, martiniil commented on prbt_default_application/CHANGELOG.rst
> +* compatible with pilz_robots version melodic-0.5.22 and noetic-0.6.0
```suggestion
* compatible with pilz_robots version 0.5.22 (melodic) or 0.6.0 (noetic) and pilz_industrial_motion version 0.4.13 (melodic) or 0.5.0 (noetic)
```

2021-07-12 16:22 UTC, martiniil requested changes
See inline comment.

I executed the launch-file with the mentioned versions. It worked.

2021-07-22 09:37 UTC, merged